name: flutter_svg_plus
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg/tree/master/packages/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
version: 2.0.13

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  vector_graphics_codec: ^1.1.11
  vector_graphics_compiler_plus: ^1.1.12
  vector_graphics_plus: ^1.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.19.0-0 <4.0.0"
  flutter: ">=3.7.0-0"
# dependency_overrides:
#   vector_graphics:
#     path: ../vector_graphics/packages/vector_graphics
#   vector_graphics_codec:
#     path: ../vector_graphics/packages/vector_graphics_codec
#   vector_graphics_compiler:
#     path: ../vector_graphics/packages/vector_graphics_compiler
